#!/usr/bin/env python3
"""Generate docs/MFFM_manual_tables.tex from the SHIPPED data files, so the manual's
per-economy appendix is accurate by construction.

Sources (read-only):
  app/public/data/bvar/<CC>/spec.json          variable id/name/transformation/prior/isFinancial/block
  app/public/data/bvar/<CC>/fiscal_meta.json   presence => fiscal bloc
  app/public/data/bvar/<CC>/external_meta.json presence => external bloc
  app/public/data/bvar/gvar/weights_24bloc.json weights rows => coupled GVAR membership
  app/public/data/coverage_manifest.json       last historical quarter, per-variable coverage

Output: docs/MFFM_manual_tables.tex  (\\input'ed by MFFM_User_Manual.tex, appendix)
Run:    python3 docs/generate_manual_tables.py   (from the repo root)
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BVAR = os.path.join(ROOT, 'app/public/data/bvar')
OUT = os.path.join(ROOT, 'docs/MFFM_manual_tables.tex')

NAMES = {
    'US': 'United States', 'EA': 'Euro area (aggregate)', 'JP': 'Japan', 'UK': 'United Kingdom',
    'CA': 'Canada', 'CN': 'China', 'CH': 'Switzerland', 'KR': 'Korea', 'MX': 'Mexico',
    'AU': 'Australia', 'TR': 'T\\"urkiye', 'SE': 'Sweden', 'PL': 'Poland', 'NO': 'Norway',
    'DK': 'Denmark', 'IN': 'India', 'BR': 'Brazil', 'RU': 'Russia', 'ID': 'Indonesia',
    'SA': 'Saudi Arabia', 'AR': 'Argentina', 'ZA': 'South Africa', 'TH': 'Thailand',
    'MY': 'Malaysia', 'CL': 'Chile', 'CO': 'Colombia', 'CR': 'Costa Rica', 'CZ': 'Czechia',
    'HU': 'Hungary', 'IL': 'Israel', 'IS': 'Iceland', 'NZ': 'New Zealand', 'TW': 'Taiwan Province of China',
    'DE': 'Germany', 'FR': 'France', 'IT': 'Italy', 'ES': 'Spain', 'NL': 'Netherlands',
    'AT': 'Austria', 'BE': 'Belgium', 'FI': 'Finland', 'GR': 'Greece', 'IE': 'Ireland',
    'LU': 'Luxembourg', 'PT': 'Portugal', 'SI': 'Slovenia', 'SK': 'Slovakia', 'EE': 'Estonia',
    'LT': 'Lithuania', 'LV': 'Latvia',
}

def esc(s):
    return (s.replace('\\', r'\textbackslash{}').replace('&', r'\&').replace('%', r'\%')
             .replace('$', r'\$').replace('#', r'\#').replace('_', r'\_')
             .replace('{', r'\{').replace('}', r'\}').replace('~', r'\textasciitilde{}')
             .replace('^', r'\textasciicircum{}'))

def main():
    # ---- load shipped data ----
    blocs = sorted(d for d in os.listdir(BVAR)
                   if os.path.isdir(os.path.join(BVAR, d))
                   and os.path.exists(os.path.join(BVAR, d, 'spec.json')))
    weights = json.load(open(os.path.join(BVAR, 'gvar/weights_24bloc.json')))
    wrows = set((weights.get('weights') or weights).keys())
    manifest = json.load(open(os.path.join(ROOT, 'app/public/data/coverage_manifest.json')))
    man = {b['code']: b for b in manifest['blocs']}

    specs, fiscal, external, coupled = {}, set(), set(), set()
    for c in blocs:
        p = os.path.join(BVAR, c)
        specs[c] = json.load(open(os.path.join(p, 'spec.json')))
        if os.path.exists(os.path.join(p, 'fiscal_meta.json')):
            fiscal.add(c)
        if os.path.exists(os.path.join(p, 'external_meta.json')):
            external.add(c)
        has_row = any(v.get('block') == 'row' for v in specs[c]['variables'])
        if has_row and c in wrows:
            coupled.add(c)

    order = [c for c in ['US', 'EA', 'JP', 'UK', 'CA', 'CN'] if c in blocs] + \
            sorted(c for c in blocs if c not in {'US', 'EA', 'JP', 'UK', 'CA', 'CN'})

    L = []
    A = L.append
    A('%% AUTO-GENERATED by docs/generate_manual_tables.py from the SHIPPED spec.json /')
    A('%% coverage_manifest.json — do not edit by hand; re-run the generator instead.')
    A('')

    # ---- Table B1: bloc summary ----
    A(r'\subsection*{B.1\quad The deployed roster at a glance}')
    A(r'\label{app:roster}')
    A(r'Generated from the shipped \texttt{spec.json}, \texttt{fiscal\_meta.json},')
    A(r'\texttt{external\_meta.json}, the trade-weights file, and the coverage manifest')
    A(r'(\texttt{coverage\_manifest.json}); the table therefore reflects the deployed data')
    A(r'exactly. $n$ counts the variables of the estimated VAR (domestic, global, fiscal, and')
    A(r'star columns included). \emph{Coupled} marks membership of the cross-country fixed point')
    A(r'(Section~\ref{sec:gvar}); the remaining blocs are standalone models. \emph{Fiscal} and')
    A(r'\emph{External} mark the accounting blocks of Section~\ref{sec:fiscal}. \emph{Last obs.}\ is')
    A(r"the bloc's last historical quarter.")
    A('')
    A(r'\begin{small}')
    A(r'\begin{longtable}{@{}llccccl@{}}')
    A(r'\caption{Deployed economies: dimension, coupling, accounting blocks, last observation.}\label{tab:roster}\\')
    A(r'\toprule')
    A(r'Code & Economy & $n$ & Coupled & Fiscal & External & Last obs. \\')
    A(r'\midrule\endfirsthead')
    A(r'\toprule')
    A(r'Code & Economy & $n$ & Coupled & Fiscal & External & Last obs. \\')
    A(r'\midrule\endhead')
    A(r'\bottomrule\endfoot')
    for c in order:
        s = specs[c]
        n = s.get('n', len(s['variables']))
        m = man.get(c, {})
        A(r'\texttt{%s} & %s & %d & %s & %s & %s & %s \\' % (
            c, NAMES.get(c, c), n,
            r'\checkmark' if c in coupled else '---',
            r'\checkmark' if c in fiscal else '---',
            r'\checkmark' if c in external else '---',
            esc(m.get('lastHistQuarter', '?'))))
    A(r'\end{longtable}')
    A(r'\end{small}')
    A('')

    # ---- Table B2: per-economy variable tables ----
    A(r'\subsection*{B.2\quad Variables, transformations, and priors by economy}')
    A(r'\label{app:vartables}')
    A(r'One block per economy, generated from the shipped \texttt{spec.json}. \emph{Trans.}:')
    A(r'\texttt{log} = the variable enters the VAR as $100\ln(\cdot)$ (growth displayed);')
    A(r'\texttt{lin} = the variable enters in levels. \emph{Prior}: RW = random-walk own-lag')
    A(r'prior mean ($\delta_i=1$), WN = stationary white-noise own-lag prior mean ($\delta_i=0$;')
    A(r'Section~\ref{sec:ownlag}). \emph{Fin.}: the \texttt{isFinancial} tag --- financial')
    A(r'variables stay \emph{observed} through the COVID window (Section~\ref{sec:covid}).')
    A(r'\emph{Block}: dom.\ = domestic, glob.\ = US-determined global common, fisc.\ = fiscal')
    A(r'driver, row = trade-weighted star, ext.\ = area-wide instrument carried as weakly')
    A(r'exogenous (euro members). The dates give the \emph{shipped} history window the')
    A(r'application loads (the recent span the charts display and the state initializes from);')
    A(r'the estimation sample is longer and ends at the 2025Q4 estimation vintage')
    A(r'(Section~\ref{sec:vintage}).')
    A('')
    BLK = {'domestic': 'dom.', 'global': 'glob.', 'fiscal': 'fisc.', 'row': 'row', 'external': 'ext.'}
    for c in order:
        s = specs[c]
        n = s.get('n', len(s['variables']))
        m = man.get(c, {})
        cov = ''
        vs = m.get('variables') or []
        if vs:
            starts = sorted(v.get('coverageStart', '') for v in vs if v.get('coverageStart'))
            if starts:
                cov = ', shipped history from %s' % esc(starts[0])
        A(r'\begin{small}')
        A(r'\begin{longtable}{@{}lp{6.4cm}cccc@{}}')
        A(r'\caption{%s (\texttt{%s}): $n=%d$%s, last observation %s.}\\' % (
            NAMES.get(c, c), c, n, cov, esc(m.get('lastHistQuarter', '?'))))
        A(r'\toprule')
        A(r'ID & Description & Trans. & Prior & Fin. & Block \\')
        A(r'\midrule\endfirsthead')
        A(r'\toprule')
        A(r'ID & Description & Trans. & Prior & Fin. & Block \\')
        A(r'\midrule\endhead')
        A(r'\bottomrule\endfoot')
        for v in s['variables']:
            A(r'\texttt{%s} & %s & \texttt{%s} & %s & %s & %s \\' % (
                esc(v['id']), esc(v.get('name', '')), v.get('transformation', '?'),
                v.get('prior', 'RW'),
                r'\checkmark' if v.get('isFinancial') else '---',
                BLK.get(v.get('block', 'domestic'), esc(str(v.get('block'))))))
        A(r'\end{longtable}')
        A(r'\end{small}')
        A('')

    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    ncoupled, nfisc, next_ = len(coupled), len(fiscal), len(external)
    ntot = sum(specs[c].get('n', 0) for c in blocs)
    print(f'wrote {OUT}: {len(blocs)} blocs ({ncoupled} coupled, {nfisc} fiscal, {next_} external), '
          f'{ntot} variables total, {len(L)} lines')

if __name__ == '__main__':
    main()
